//workouts action types

export const CREATE_WORKOUT = "CREATE_WORKOUT";
export const FETCH_ALL_WORKOUTS = "FETCH_ALL_WORKOUTS";
export const FETCH_SINGLE_WORKOUT = "FETCH_SINGLE_WORKOUT";
export const DELETE_WORKOUT = "UPDATE_WORKOUT";
